### ISSUE TITLE
UnboundLocalError: local variable 'header' referenced before assignment

### ISSUE THREAD

**Issue by Enrichmentmapmademedothis** [gamcil/cblaster#10]
I have a single protein.fa file and the following is outputted when I run the standard search function.

u1897925$ cblaster search --query_file HGRIS_000138.fa 
Traceback (most recent call last):
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/bin/cblaster", line 10, in <module>
    sys.exit(main())
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/lib/python3.8/site-packages/cblaster/main.py", line 286, in main
    cblaster(
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/lib/python3.8/site-packages/cblaster/main.py", line 178, in cblaster
    sequences=helpers.get_sequences(
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/lib/python3.8/site-packages/cblaster/helpers.py", line 145, in get_sequences
    sequences = parse_fasta(query)
  File "/Users/u1897925/PycharmProjects/personalBLAST/venv/lib/python3.8/site-packages/cblaster/helpers.py", line 68, in parse_fasta
    sequences[header] += line
UnboundLocalError: local variable 'header' referenced before assignment

I deleted and reinstalled cblaster using the $ pip3 install cblaster command on the 15th November
The error still happens

**Comment by gamcil** [comment]
Could you upload your FASTA file? I think there is an issue with parsing the sequence names.

**Comment by Enrichmentmapmademedothis** [comment]
Thanks for the fast response, I'm not sure how to upload files, so will just paste the raw text within the 3 files I attempted (All gave the same response).

**Comment by Enrichmentmapmademedothis** [comment]
>HGRIS_000138
MPSWNDILEINKSFAPKYDSPVAIFLGGTSGVGRAMAEAFARYTGGKAHIVIIGRNRRAAQASIDTFPKPTSGTFTHEFV
ECDVSLMKNVREVTSVLVKRLPKVNFLVMSTGVFVLTGRNETVEGIDEKMALNYYARWKFTHDLLPLLRKAADAGEDARV
FSLMGAGGGKPVDMGDLGLKRTHTVMGCVSTLATYNDMMMEKFSLLAPSVSFTHGFPGPVRSPMMTPTSWLFKPIFYALY
PLVCLVTVAPETSAEYQLSALLSAGKGFNSTGARGERLPPTSSKPEDLQKLWEHTVQCTGT

**Comment by Enrichmentmapmademedothis** [comment]
>HGRIS_000138 HGRIS_000138
MPSWNDILEINKSFAPKYDSPVAIFLGGTSGVGRAMAEAFARYTGGKAHIVIIGRNRRAAQASIDTFPKPTSGTFTHEFV
ECDVSLMKNVREVTSVLVKRLPKVNFLVMSTGVFVLTGRNETVEGIDEKMALNYYARWKFTHDLLPLLRKAADAGEDARV
FSLMGAGGGKPVDMGDLGLKRTHTVMGCVSTLATYNDMMMEKFSLLAPSVSFTHGFPGPVRSPMMTPTSWLFKPIFYALY
PLVCLVTVAPETSAEYQLSALLSAGKGFNSTGARGERLPPTSSKPEDLQKLWEHTVQCTGT

**Comment by Enrichmentmapmademedothis** [comment]
Thanks for the fast response, I will now upload the three files I used, all gave the same response on my MacOS, and Linux.

**Comment by Enrichmentmapmademedothis** [comment]
It says it doesn't support the .fasta file type upload so here is a link to the files I tried.

https://livewarwickac-my.sharepoint.com/:u:/g/personal/u1897925_live_warwick_ac_uk/EcBGx8RS2RdIsbxCMmxNYHoBnfdMkXC6W7BuL9DCskB7dQ?e=KzkMbQ

https://livewarwickac-my.sharepoint.com/:u:/g/personal/u1897925_live_warwick_ac_uk/EWCm_PR4aLZOrelFYronj48Bjg9QuEN6GssQ4ITHbDjjgA?e=wNyStv

https://livewarwickac-my.sharepoint.com/:u:/g/personal/u1897925_live_warwick_ac_uk/EYRM-ToSo6JKk0CepftdLBMB_NG4YTHK0IRR4XI0bYRvmQ?e=nArtku

**Comment by gamcil** [comment]
Those links don't seem to work for me. Could you try renaming the .fasta extension to .txt on your files, then you should be able to upload them here.

**Comment by Enrichmentmapmademedothis** [comment]
Sorry for the delay, here they are as .txt files.
[HGRIS_000138.txt](https://github.com/gamcil/cblaster/files/5561182/HGRIS_000138.txt)
[HGRIS_000138_3.txt](https://github.com/gamcil/cblaster/files/5561190/HGRIS_000138_3.txt)
[HGRIS_000138_2.txt](https://github.com/gamcil/cblaster/files/5561191/HGRIS_000138_2.txt)

Normally they're just called HGRIS_000138.fa or .fasta

**Comment by gamcil** [comment]
HGRIS_000138 and HGRIS_000138_2 both load in fine for me, I only get the error with HGRIS_000138_2 which only has sequence and no header. Would you be able to try again with those 2 files and post the output? `cblaster` requires a header line for each sequence, because it expects a set of proteins in a multi FASTA file - do you want to search these sequences together or separately?

**Comment by Enrichmentmapmademedothis** [comment]
Fixed, they were being outputted by my protein prediction program as .rtf files and changing them to .fa files, this was introducing all sorts of oddities, when saved as a .txt and then renamed to .fa they now work. Thanks for the help. I do have multiple proteins to search but just wanted to get to grips with it first. Thanks again
