### ISSUE TITLE
Unable to make database. genome_parser function returning empty list.

### ISSUE THREAD

**Issue by StefaanVerwimp** [gamcil/cblaster#40]
The command `cblaster makedb Downloads/*.gbk -n test` returns:
```
File "/home/stve/.local/lib/python3.9/site-packages/cblaster/database.py", line 185, in makedb
    path_groups = [paths[i : i + batch] for i in range(0, total_paths, batch)]
ValueError: range() arg 3 must not be zero
```
This is because the return value from [`find_files_at_path`](https://github.com/gamcil/cblaster/blob/374e284de6a86db0fb140d7bbec25f1b643369d2/cblaster/genome_parsers.py#L156) in genome_parsers.py is an empty list

Reverting [this commit](https://github.com/gamcil/cblaster/commit/85fdf9a2186d1b0177d6302107a1c4c6bebb1ac1#diff-64a8c7957abb0ce94a3c6622d4132b629803a86bb5218555094b5b0844f9559b) fixed the issue for me.

**Comment by gamcil** [comment]
Thanks for reporting this, I've reverted the commit for v1.2.8.
