### ISSUE TITLE
invalid Entrez search term

### ISSUE THREAD

**Issue by onyonderlea** [gamcil/cblaster#52]
I'm getting this when trying to do a simple search against fungal genomes: 

`cblaster: error: unrecognized arguments: --eq txid4751[orgn]`

The command is basically taken from the user guide and looks like this: 

`cblaster search -qf chi.fasta --eq "txid4751[orgn]"`

Also, the link that is supposed to help with building Entrez search queries is broken:  https://cblaster.readthedocs.io/en/latest/guide/%3Chttps://www.ncbi.nlm.nih.gov/books/NBK3837%3E%60

**Comment by onyonderlea** [comment]
Ah, got it - was just an extra "-" at the eq option. But maybe you could update that in the manual and check the NCBI link :)

**Comment by gamcil** [comment]
Thanks for the heads up! Glad you got it sorted, will update those now.
