### ISSUE TITLE
LONG TIME

### ISSUE THREAD

**Issue by zuoyang97** [gamcil/cblaster#53]
dear Cameron
    I had a problem,Maybe my file is too big to run, after "INFO - Retrieving results for search 8M7EP58F013",can't proceed to Next step.

**Comment by gamcil** [comment]
Hi @zuoyang97,

Since cblaster uses the NCBI servers to retrieve this information, it can take a while to download all of your results (especially with big searches). If you leave this running, it should finish eventually.

Also, in some terminals, the output does not refresh, so you can try just pressing enter in the terminal to see if it updates.

**Comment by zuoyang97** [comment]
thank you for the response,But the question still bothers me,the program have running overnight,It's still running,But there was no sign of uploads or downloads.(**VMware** workstation:**UBUNTU** was  the device on which I run the program)
![image](https://user-images.githubusercontent.com/82920312/116768781-cd72af80-aa6b-11eb-8774-e84c4f71e6ce.png)
![屏幕截图 2021-05-01 110118](https://user-images.githubusercontent.com/82920312/116769142-a668ad80-aa6c-11eb-9248-66e8b5a2ff92.png)

**Comment by gamcil** [comment]
Hmm that's weird, the only thing I can suggest is to try starting a new search and see if it works.

Could you upload your file here so I could look at it?

**Comment by zuoyang97** [comment]
I appreciate your helping me，this is my file. and I tried to construct a database from folders, but I failed.  can you help me?
(base) lzy@ubuntu:~$  cblaster makedb /home/lzy/datebase myDb
usage: cblaster makedb [-h] -n NAME [-cp CPUS] [-b BATCH] [-f] paths [paths ...]
cblaster makedb: error: argument paths: Invalid path: '/home/lzy/datebase'.

(base) lzy@ubuntu:~$ cblaster makedb genomes /home/lzy/datebase/
usage: cblaster makedb [-h] -n NAME [-cp CPUS] [-b BATCH] [-f] paths [paths ...]
cblaster makedb: error: argument paths: Invalid path: 'genomes'.

**Comment by gamcil** [comment]
It doesn't seem like a file was uploaded, could you try again? Maybe you can just copy paste your FASTA file into a message here.

For the local database, are your files inside ``/home/Izy/datebase/``? cblaster expects multiple files, like:

``cblaster makedb genome1.gbk genome2.gbk genome3.gbk myDb``

If your files are inside ``/home/Izy/datebase/``, you can use a wildcard to do this:

``cblaster makedb /home/Izy/datebase/*.gbk myDb``

**Comment by zuoyang97** [comment]
[Chr1.region025.zip](https://github.com/gamcil/cblaster/files/6418834/Chr1.region025.zip)
Yes, the folder I want to enter contains multiple files.Because of the large number of files and the complexity of naming, I want to type them all at once, rather than one at a time
thanks！

**Comment by gamcil** [comment]
Your file has ~50 sequences in it, so it definitely will take a while! It should still finish eventually though. Could you try running cblaster again with a smaller subset of your sequences and see if that works? You could also try a lower``-hs/--hitlist_size`` to make cblaster retrieve fewer results after a BLAST search (by default, this is 5000 - you could lower to 500-1000).

Once your local database is working, this search should go a lot quicker :)

**Comment by zuoyang97** [comment]
Thanks for your help, I lowered the size of hs/ -- hitlist and the  online-blast problem was solved.
Due to the problem of conda, I cannot run my own database for the time being. I am looking forward to its operation.

**Comment by gamcil** [comment]
Ah, I'm happy the online search is working for you now. Not sure about conda, previously some people have had issues with the version of BioPython that gets installed, so maybe you can try to upgrade it.
