### ISSUE TITLE
extract error -de expected one argument

### ISSUE THREAD

**Issue by mafeeney** [gamcil/cblaster#55]
I ran: 
cblaster extract .\Streptomyces-session.json -q "SCO5318" -d -o SCO5318hits.fasta 
to extract hits from a previously run session, but I got the following error message:

cblaster extract: error: argument -de/--delimiter: expected one argument

I tried repeating the search, but with the addition of -de "," and got the same error message.

I am not sure what I've done wrong - would appreciate any help! Thank you!!

**Comment by gamcil** [comment]
Ahh it looks like the help for that module is a little out of date - the -d argument no longer exists, and should be -es (for extract_sequences) instead.

So you should do:
`cblaster extract .\Streptomyces-session.json -q "SCO5318" -es -o SCO5318hits.fasta`

**Comment by mafeeney** [comment]
ah, thank you so much!!
