### ISSUE TITLE
Red and orange borders in heat map

### ISSUE THREAD

**Issue by aberaslop** [gamcil/cblaster#64]
Hi!
Thank you so much for such a useful tool. 
I have installed and run the program without any problems. At the time of exploring the results, I noticed that in some of the resulting heatmaps, some cells have a red or orange border. I have read the manuscript in bioarxiv, but I haven't seen any reference to these colors. What do they mean? Thanks a lot!

L.

**Comment by gamcil** [comment]
Hi @aberaslop, thanks for using the tool. Cells with these borders contain hits to the same subject sequence (i.e. query sequences A and B both hit subject sequence C in the BLAST search). If this happens for multiple different subject sequences, each different group is given a different colour (hence the red and orange). Hope that helps!

**Comment by aberaslop** [comment]
Hi @gamcil,
Thank you so much for your answer! This is very helpful. Thank you again for such a great tool!
