### ISSUE TITLE
How to plot output after using "hmm" mode?

### ISSUE THREAD

**Issue by laelbarlow** [gamcil/cblaster#69]
Hi, I want to generate a plot with clinker, but can't seem to figure out how to extract the results from the session.json file after running cblaster search in "hmm" mode. cblaster extract_clusters gives this error: "NotImplementedError: No protocol for mode hmm".

**Comment by gamcil** [comment]
Hi, thanks for letting me know - should be fixed in v1.3.12. Could you update and try again?

**Comment by laelbarlow** [comment]
It works now with the update to v1.3.12. Thank you!
