### ISSUE TITLE
Error encode in database create.

### ISSUE THREAD

**Issue by Maiya19724** [gamcil/cblaster#72]
Hi,@gamcil ! Thank you for developing this useful tool and I have some issues below.

1.
When I try to create a database with gb,gbff,gbk,gff+fasta files, the following errors appears.
`**Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "cblaster\gui\main.py", line 339, in run
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 11: invalid start byte**`

2.
When there are too many input files(About 2,000 to 3,000), the following error will appear in cblaster.
`**Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "cblaster\gui\main.py", line 326, in run
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 206] The filename or extension is too long.**`

The input file used is attached below.
[issue1-19.zip](https://github.com/gamcil/cblaster/files/7897304/issue1-19.zip)

Thanks again for your help.

**Comment by Tim-Kirkwood** [comment]
The second error is windows specific, not CBLASTER (I think) - can you try linux?  If there is a workaround please let me know, I had to get a friend to make a DB for me because of this!

**Comment by Maiya19724** [comment]
> The second error is windows specific, not CBLASTER (I think) - can you try linux? If there is a workaround please let me know, I had to get a friend to make a DB for me because of this!

Sorry for the late reply. Do you still need this database? I can help you build it, or we could try discussing further since it looks like our research directions might align. @Tim-Kirkwood
