### ISSUE TITLE
Local runs fail with `-bat identity -bkey max`

### ISSUE THREAD

**Issue by chasemc** [gamcil/cblaster#76]
Not going to PR because I haven't looked into how all the code interacts, but 

`cblaster search -m local -db... -bat identity -bkey max`

fails, and it seems to be caused when there's no hits. 
```
python3.9/site-packages/cblaster/formatters.py", line 64, in get_cell_values
    result[index] = key(values)
ValueError: max() arg is an empty sequence
```

Relevant code:

https://github.com/gamcil/cblaster/blob/8b6d97e0a5c94f11e791edbdb31a07cd5b085fa4/cblaster/formatters.py#L58-L64

**Comment by gamcil** [comment]
Fixed with #77
