### ISSUE TITLE
extract_clusters off by a bp

### ISSUE THREAD

**Issue by galacmr** [gamcil/cblaster#83]
I discovered that the annotations in gbk files produced by extract_clusters are shortened by 1 bp. It looks to be whichever gene end is at the 3' end of the gbk file. If that end is the start of the protein then the whole translation is messed up. Note that the cblaster gbk sequence is reversed complimented in the image. 
![cblaster_issue](https://user-images.githubusercontent.com/74789332/196484659-1a8e0269-6cd7-46be-b211-d694a02d67f4.png)
This definitely leads to issues analyzing the clusters identified by cblaster in downstream analyses.

**Comment by gamcil** [comment]
Thanks @galacmr. Is it possible to upload any of the files generated by cblaster here?

**Comment by galacmr** [comment]
Definitely! Here is the gbk file I used to make that image. 
[05_E-Cluster1348.gbk.zip](https://github.com/gamcil/cblaster/files/9839895/05_E-Cluster1348.gbk.zip)
Let me know if the json session file or some other files would also be useful, though I will say that for this particular search there were 1000s of results.

**Comment by gamcil** [comment]
Thanks for uploading that, the session file would also definitely still be useful if you still have it :)

**Comment by galacmr** [comment]
Here you go! Let me know if you need anything else
[cblaster_session_2022-3-2.json.zip](https://github.com/gamcil/cblaster/files/9851905/cblaster_session_2022-3-2.json.zip)

**Comment by galacmr** [comment]
Hello! I was wondering if there was any update on this? Thanks!

**Comment by gamcil** [comment]
Hey, sorry for the delay. Could you see if you still have the same problem starting from a fresh search? I made a change to correct fetching genomic coordinates when getting them from the NCBI (https://github.com/gamcil/cblaster/commit/9cffe3968437a895302e3886c77d61371aa93d4b) but not sure if it fully addresses your issue.

**Comment by gamcil** [comment]
Sorry this is taking a while to figure out. Could you try installing cblaster from the `fixextract` branch using:

`pip install git+https://www.github.com/gamcil/cblaster@fixextract`

And then run a new cblaster search? I made a few changes to how the coordinates are set when retrieving genes from the NCBI. If there are any issues with extracting clusters from that search, if you could provide the session/query files it would be really helpful.

**Comment by galacmr** [comment]
This looks to have fixed both the original problem and the secondary problem! The extraction annotations looks to be correct now. Thanks so much!

**Comment by gamcil** [comment]
Great, thanks for testing it out. Will merge in those changes and make a new release.
